tecnicas/apps/mactor/urls.py
from django.conf.urls import url
from .views import index, prueba, matriz_mid, matriz_1mao, matriz_2mao, matriz_3mao
from .views import Crear_estudio, Listar_actor, Crear_actor, Editar_actor, Eliminar_actor, Crear_ficha, \
    Crear_objetivo, Listar_objetivo, Editar_objetivo, Eliminar_objetivo, Crear_relacionInfluencia, Crear_1mao,\
    Crear_2mao
from .views import actor_ajax, consultar_ficha, consultar_desc_obj

# nombre de la url, view que respondera y el parametro name
urlpatterns = [
    url(r'^$', index, name=index),
    url(r'^prueba$', matriz_1mao, name='matriz_1mao'),

# Urls modelo Estudio_mactor
    url(r'^estudio$', Crear_estudio.as_view(), name='formEstudio'),

# Urls modelo Actor
    url(r'^actor$', Crear_actor.as_view(), name='formActor'),
    url(r'^lista_actores', Listar_actor.as_view(), name='listar_actor'),
    url(r'^editar_actor/(?P<pk>\d+)/$', Editar_actor.as_view(), name='editar_actor'),
    url(r'^eliminar_actor/(?P<pk>\d+)/$', Eliminar_actor.as_view(), name='eliminar_actor'),

# Urls modelo ficha_actor
    url(r'^ficha$', Crear_ficha.as_view(), name='ficha'),

# Urls modelo Objetivo
    url(r'^objetivo$', Crear_objetivo.as_view(), name='objetivo'),
    url(r'^lista_objetivos', Listar_objetivo.as_view(), name='listar_objetivo'),
    url(r'^editar_objetivo/(?P<pk>\d+)/$', Editar_objetivo.as_view(), name='editar_objetivo'),
    url(r'^eliminar_objetivo/(?P<pk>\d+)/$', Eliminar_objetivo.as_view(), name='eliminar_objetivo'),

# Urls modelo influencias y matrices
    url(r'^influencia$', Crear_relacionInfluencia.as_view(), name='influencia'),
    url(r'^matriz_mid$', matriz_mid, name='matriz_mid'),
    url(r'^1mao$', Crear_1mao.as_view(), name='1mao'),
    url(r'^matriz_1mao$', matriz_1mao, name='matriz_1mao'),
    url(r'^2mao$', Crear_2mao.as_view(), name='2mao'),
    url(r'^matriz_2mao$', matriz_2mao, name='matriz_2mao'),
    url(r'^matriz_3mao$', matriz_3mao, name='matriz_3mao'),

# Urls peticiones ajax
    url(r'^actor-ajax/$', actor_ajax),
    url(r'^actor-ajax2/$', consultar_ficha),
    url(r'^objetivo-ajax/$', consultar_desc_obj),





]

tecnicas/tecnicas/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # urls del administrador
    url(r'^admin/', include(admin.site.urls)),
    # urls de la app mactor
    url(r'^mactor/', include('apps.mactor.urls', namespace="mactor")),
]

tecnicas/apps/mactor/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponse, request
from .models import Estudio_Mactor, Actor, Ficha_actor, Objetivo, Relacion_Influencia, Relacion_MAO
from .forms import Formulario_Estudio, Formulario_actor, Formulario_Ficha, Formulario_objetivo, Formulario_Influencia, \
    Formulario_1mao, Formulario_2mao
from django.views.generic import ListView, CreateView, UpdateView, DeleteView



# VIEW MODELO ESTUDIO MACTOR------------------------------------------------------------------------------------>

class Crear_estudio(CreateView):
    model = Estudio_Mactor
    form_class = Formulario_Estudio
    template_name = 'Estudio/create_estudio.html'
    success_url = reverse_lazy('mactor:formActor')


# VIEWS MODELO ACTOR-------------------------------------------------------------------------------------------->

class Crear_actor(CreateView):
    model = Actor
    form_class = Formulario_actor
    template_name = 'actor/create_actor.html'
    success_url = reverse_lazy('mactor:listar_actor')


class Listar_actor(ListView):
    model = Actor
    template_name = 'actor/list_actor.html'
    paginate_by = 15
    ordering = ('nombreLargo',)


class Editar_actor(UpdateView):
    model = Actor
    form_class = Formulario_actor
    template_name = 'actor/create_actor.html'
    success_url = reverse_lazy('mactor:listar_actor')


class Eliminar_actor(DeleteView):
    model = Actor
    template_name = 'actor/delete_actor.html'
    success_url = reverse_lazy('mactor:listar_actor')

# VIEWS MODELO FICHA ACTOR-------------------------------------------------------------------------------------------->

class Crear_ficha(CreateView):
    model = Ficha_actor
    form_class = Formulario_Ficha
    template_name = 'Ficha/create_ficha_actor.html'
    success_url = reverse_lazy('mactor:ficha')


# VIEWS FORMULARIO OBJETIVO------------------------------------------------------------------------------------->

class Crear_objetivo(CreateView):
    model = Objetivo
    form_class = Formulario_objetivo
    template_name = 'objetivo/create_objetivo.html'
    success_url = reverse_lazy('mactor:listar_objetivo')


class Listar_objetivo(ListView):
    model = Objetivo
    template_name = 'objetivo/list_objetivo.html'
    paginate_by = 15


class Editar_objetivo(UpdateView):
    model = Objetivo
    form_class = Formulario_objetivo
    template_name = 'objetivo/create_objetivo.html'
    success_url = reverse_lazy('mactor:listar_objetivo')


class Eliminar_objetivo(DeleteView):
    model = Objetivo
    template_name = 'objetivo/delete_objetivo.html'
    success_url = reverse_lazy('mactor:listar_objetivo')


# VIEWS INFLUENCIAS DIRECTAS E INDIRECTAS----------------------------------------------------------------------->

# Ingresa las influencias con valor 0 de un actor sobre si mismo
def auto_influencia():  # debe recibir posteriormente el codigo del estudio, usuario
    # registro de la influencia de un actor sobre si mismo automaticamente = 0
    actor = Actor.objects.all().order_by('id')
    usu = User.objects.all().order_by('id')
    inf = Relacion_Influencia.objects.all().order_by('id')
    cont = 0

    for i in inf:
        if i.actorX == i.actorY:
            cont += 1
    if cont == 0:
        for j in range(len(actor)):
            a = Relacion_Influencia()
            a.actorX = actor[j]
            a.actorY = actor[j]
            a.valor = 0
            a.creador = usu[1]
            a.justificacion = ""
            a.codigo_Estudio = 1
            a.save()

class Crear_relacionInfluencia(CreateView):
    model = Relacion_Influencia
    form_class = Formulario_Influencia
    template_name = 'influencia/create_influencia.html'
    success_url = reverse_lazy('mactor:influencia')
    auto_influencia()


# View generadora de la matriz MID
def matriz_mid(request):

    actor = Actor.objects.all().order_by('id')
    inf = Relacion_Influencia.objects.all().order_by('actorY', 'actorX')
    valores = []    # contiene los valores que se muestran en la matriz
    cont = 0        # cuenta las influencias
    pos_list = 0    # determina el nombre corto que se ha de colocar en valores
    influencia = 0
    dependencia = 0

    for i in range(len(inf)):
        cont += 1
        valores.append(Valor_posicion(posicion=cont, valor=inf[i].valor))
        influencia += inf[i].valor  # se suman los valores de influencia directa
        if cont == actor.count():
            # se agrega el valor de la sumatoria de influencia directa del actor correspondiente
            valores.append(Valor_posicion(posicion=cont + 1, valor=influencia))
            # determina la posicion donde se va a colocar el nombre corto de la nueva fila
            cont2 = (actor.count() + 2) * pos_list
            # inserta el nombre corto de la nueva fila
            valores.insert(cont2, Valor_posicion(posicion=0, valor=actor[pos_list].nombreCorto))
            cont = 0
            pos_list += 1
            influencia = 0  # reinicio del valor de influencia

    # Agregado de la sumatoria de dependencias directas
    valores.append(Valor_posicion(posicion=0, valor="Dep. D"))
    cont = 1
    while cont <= actor.count():
        for i in valores:
            if i.posicion == cont:
                dependencia += i.valor
        valores.append(Valor_posicion(posicion=cont, valor=dependencia))
        cont += 1           # iteracion de las posiciones
        dependencia = 0     # reinicio a o del valor movilizacion

    midi = calcular_midi()  # obtencion de la matriz midi

    contexto = {'actores': actor, 'cantidad_mid': actor.count() + 1, 'cantidad_midi': actor.count() + 1,
                'valores': valores, 'valores_midi': midi}
    return render(request, 'influencia/matriz.html', contexto)

# VIEWS MATRIZ 1MAO---------------------------------------------------------------------------------------------------->

class Crear_1mao(CreateView):
    model = Relacion_MAO
    form_class = Formulario_1mao
    template_name = 'mao/create_1mao.html'
    success_url = reverse_lazy('mactor:1mao')

# View generadora de la matriz 1mao
def matriz_1mao(request):

    lista = generar_matriz_mao(2)                       # lista que contiene los parametros del contexto
    objetivo = Objetivo.objects.all().order_by('id')    # objetivos registrados
    actor = Actor.objects.all().order_by('id')          # actores registrados

    # objetivos:   lista de objetivos
    # actores:     lista de actores
    # valores:     valores de la matriz 2mao
    # cantidad:    cantidad de columnas, ayuda a establecer cuando hacer el salto de fila
    # cantidad2:   cantidad de columnas para las sumatorias de movilizacion (ultimas 3 filas)
    # valores_caa: valores de la matriz de convergencias
    # valores_daa: valores de la matriz de divergencias

    contexto = {'objetivos': lista[0], 'actores': lista[1], 'valores': lista[2], 'cantidad': objetivo.count() + 3,
                'cantidad2': lista[3], 'valores_caa': lista[4], 'cantidad3': actor.count(),
                'valores_daa': lista[5]}
    return render(request, 'mao/matriz_1mao.html', contexto)


# VIEWS MATRIZ 2MAO---------------------------------------------------------------------------------------------------->

class Crear_2mao(CreateView):
    model = Relacion_MAO
    form_class = Formulario_2mao
    template_name = 'mao/create_2mao.html'
    success_url = reverse_lazy('mactor:2mao')


# View generadora de la matriz 2mao
def matriz_2mao(request):

    lista = generar_matriz_mao(1)
    objetivo = Objetivo.objects.all().order_by('id')  # objetivos registrados
    actor = Actor.objects.all().order_by('id')  # actores registrados

    contexto = {'objetivos': lista[0], 'actores': lista[1], 'valores': lista[2], 'cantidad': objetivo.count() + 3,
                'cantidad2': lista[3], 'valores_caa': lista[4], 'cantidad3': actor.count(),
                'valores_daa': lista[5]}
    return render(request, 'mao/matriz_2mao.html', contexto)


# -------------------------------------CLASES AUXILIARES--------------------------------------------------------------->

# Clase auxiliar para la generacion de matrices, se asigna una posicion a un respectivo valor
class Valor_posicion:
    def __init__(self, posicion, valor):
        self.posicion = posicion
        self.valor = valor


# -------------------------------------FUNCIONES AUXILIARES------------------------------------------------------------>

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<Funciones influencias entre actores>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# Geracion de la matriz MIDIij = MID ij + Sum(Minimo [(MID ik, MID ik])
def calcular_midi():
    actor = Actor.objects.all().order_by('id')
    inf = Relacion_Influencia.objects.all().order_by('actorY', 'actorX')
    lista_minimo = []     # contiene las sublistas de valores minimos por cada actor Y
    lista_total = []      # contiene lista_minimo concatenado
    valores_midi = []     # contiene los valores correspondientes a MIDI

    # se agrega la sublista de valores minimos correspondiente al actorY a lista_minimo
    for i in range(len(inf)):
        if inf[i].actorY == inf[i].actorX:
            lista_minimo.append(calcular_minimo(pos=i))  # cada valor de pos permite el calculo de una fila de la matriz

    # concatenacion de lista_minimo para facilitar la suma con las influencias correspondientes (igual longitud)
    for i in lista_minimo:
        lista_total += i

    cont = 0
    pos_list = 0
    li = 0
    # se realiza la suma MID ij + Sum(Minimo [(MID ik, MID ik])
    for i in range(len(inf)):
        cont += 1
        valores_midi.append(Valor_posicion(posicion=cont, valor=inf[i].valor + lista_total[i]))
        # calcula el valor li
        if inf[i].actorY != inf[i].actorX and cont <= actor.count():
            li += inf[i].valor + lista_total[i]

tecnicas/apps/mactor/templates/mao/create_1mao.html
{% extends 'base\baseMactor.html' %}
{% load staticfiles %}

{% block pull-left %}
<h2>Relación 1MAO</h2>
{% endblock %}

{% block content %}

<div class="matter">
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<div class="widget wgreen">
              						<div class="widget-head">
									  <div class="pull-left">Formulario - Matriz Valorada de posiciones</div>
									  <div class="clearfix"></div>
									</div>
									<div class="widget-content">
									  <div class="padd">

										<hr/>
										<!-- Form starts.  -->
											<form class="form-horizontal" role="form" method="post">
                                            {% csrf_token %}

												<div class="col-md-3 col-md-offset-1">
                                                	<div  class="row">
                                                		<div class="form-group">
												  			<label class="control-label">Tipo</label>
															<input class="form-control" type="number" value="1" name="tipo">
														</div>
                                                	</div>
                                                </div>

												<div class="row">
													<div class="col-md-7 col-md-offset-1">
                                                		<div class="form-group">
                                                    		{{form.actorY.errors}}
												 			 <label class="control-label">Relación del actor</label>
															{{form.actorY}}
														</div>
													</div>
												</div>

                                                <div class="row">
                                                    <div class="col-md-7 col-md-offset-1">
                                                        <div id="info" style='text-align: justify'></div>
                                                    </div>
                                                </div>

												<div class="row">
													<div class="col-md-7 col-md-offset-1">
														<div class="form-group">
															{{form.objetivoX.errors}}
												  			<label class="control-label">Sobre el objetivo</label>
                                                    		{{form.objetivoX}}
														</div>
													</div>


                                                	<div class="col-md-2 col-md-offset-1">
														<div class="form-group">
												  			<label class="control-label">Valor</label>
															<br>
												  			{{form.valor}}
														</div>
													</div>
												</div>

                                                <div class="row">
                                                    <div class="col-md-7 col-md-offset-1">
                                                        <div id="info2" style="text-align: justify"></div>
                                                    </div>
                                                </div>


                                                <div class="row">
                                                	<div class="col-md-7 col-md-offset-1">
														<div class="form-group">
												  			<label class="control-label">Justificación</label>
												  			{{form.justificacion}}
														</div>
                                                	</div>
                                                </div>

												<div  class="row">
                                                	<div class="col-md-3 col-md-offset-1">
                                                		<div class="form-group">
												  			<label class="control-label">Experto</label>
												 			{{form.creador}}
														</div>
                                                	</div>


												    <div class="col-md-3 col-md-offset-1">
													    <div class="form-group">
														    <label class="control-label">Código Estudio</label>
														    {{form.codigo_Estudio}}
													    </div>
												    </div>
                                                </div>


                                                <div class="form-group">
                                                    <div class="col-md-offset-2 col-md-8">
														<a class="btn btn-sm btn-success" href="{%url 'mactor:matriz_mid'%}"><i class="fa fa-arrow-left"></i> Atrás</a>
                                                        <button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i>Guardar</button>
                                                        <a class="btn btn-primary" data-toggle="modal" href="#myModal"><i class="fa fa-book"></i> Ayuda</a>
                                                        <a class="btn btn-sm btn-success" href="{%url 'mactor:matriz_1mao'%}">Matriz <i class="fa fa-arrow-right"></i></a>
                                                    </div>
												</div>

                     <! INICIO MODAL AYUDA--------------------------->

                    <div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
								<div class="modal-dialog">
								     <div class="modal-content">
								     <div class="modal-header">
									<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
									<h4 class="modal-title">Ayuda</h4>
								     </div>
								     <div class="modal-body">
									<p>Ingrese el nivel de influencia que posee un actor respecto a los demás...</p>
								     </div>
								  <div class="modal-footer">
									<button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cerrar</button>
								  </div>
								    </div>
								</div>
                    </div>

                    <! FINAL MODAL AYUDA--------------------------->
											</form>
									  </div>
									</div>
								</div>


							</div>
						</div>
					</div>
</div>

{% block extrajs %}
<script src="{% static 'jquery/jquery.min.js' %}"></script>
<script src="{% static 'js_mactor/consultas_ajax.js' %}"></script>
<script src="{% static 'js_mactor/consultas_ajax2.js' %}"></script>
{% endblock %}

{% endblock %}

tecnicas/apps/mactor/templates/mao/create_2mao.html
{% extends 'base\baseMactor.html' %}
{% load staticfiles %}

{% block pull-left %}
<h2>Relación 2MAO</h2>
{% endblock %}

{% block content %}

<div class="matter">
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<div class="widget wgreen">
              						<div class="widget-head">
									  <div class="pull-left">Formulario - Matriz Valorada de posiciones</div>
									  <div class="clearfix"></div>
									</div>
									<div class="widget-content">
									  <div class="padd">

										<hr/>
										<!-- Form starts.  -->
											<form class="form-horizontal" role="form" method="post">
                                            {% csrf_token %}

												<div class="col-md-3 col-md-offset-1">
                                                	<div  class="row">
                                                		<div class="form-group">
															<label class="control-label">Tipo</label>
															<input class="form-control" type="number" value="2" name="tipo">
														</div>
                                                	</div>
                                                </div>

												<div class="row">
													<div class="col-md-7 col-md-offset-1">
                                                		<div class="form-group">
                                                    		{{form.actorY.errors}}
												  			<label class="control-label">Relación del actor</label>
                                                    		{{form.actorY}}
														</div>
													</div>
												</div>

                                                <div class="row">
                                                    <div class="col-md-7 col-md-offset-1">
                                                        <div id="info" style="text-align: justify"></div>
                                                    </div>
                                                </div>

												<div class="row">
													<div class="col-md-7 col-md-offset-1">
														<div class="form-group">
															{{form.objetivoX.errors}}
												  			<label class="control-label">Sobre el objetivo</label>
                                                    		{{form.objetivoX}}
														</div>
													</div>


                                                	<div class="col-md-2 col-md-offset-1">
														<div class="form-group">
															<label class="control-label">Valor</label>
															<br>
													  		{{form.valor}}
														</div>
													</div>
												</div>

                                                <div class="row">
                                                    <div class="col-md-7 col-md-offset-1">
                                                        <div id="info2" style="text-align: justify"></div>
                                                    </div>
                                                </div>


                                                <div class="row">
                                                	<div class="col-md-7 col-md-offset-1">
														<div class="form-group">
														  <label class="control-label">Justificación</label>
														  {{form.justificacion}}
														</div>
                                                	</div>
                                                </div>

												<div  class="row">
                                                	<div class="col-md-3 col-md-offset-1">
                                                		<div class="form-group">
												  			<label class="control-label">Experto</label>
												 			{{form.creador}}
														</div>
                                                	</div>

                                                	<div class="col-md-3 col-md-offset-1">
														<div class="form-group">
												  			<label class="control-label">Código Estudio</label>
												 			{{form.codigo_Estudio}}
														</div>
                                               		 </div>
												</div>

												<div class="form-group">
												  <div class="col-md-offset-2 col-md-8">
													   <a class="btn btn-sm btn-success" href="{%url 'mactor:matriz_1mao'%}"><i class="fa fa-arrow-left"></i> Atrás</a>
                                                     	<button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i> Guardar</button>
													  	<a class="btn btn-primary" data-toggle="modal" href="#myModal"><i class="fa fa-book"></i> Ayuda</a>
                                                      	<a class="btn btn-sm btn-success" href="{%url 'mactor:matriz_2mao'%}">Matriz <i class="fa fa-arrow-right"></i></a>
												  </div>

                    <! INICIO MODAL AYUDA--------------------------->

                    <div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
								<div class="modal-dialog">
								     <div class="modal-content">
								     <div class="modal-header">
									<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
									<h4 class="modal-title">Ayuda</h4>
								     </div>
								     <div class="modal-body">
									<p>Ingrese el nivel de influencia que posee un actor respecto a los demás...</p>
								     </div>
								  <div class="modal-footer">
									<button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cerrar</button>
								  </div>
								    </div>
								</div>
                    </div>

                    <! FINAL MODAL AYUDA--------------------------->



												</div>
											</form>
									  </div>
									</div>
								</div>


							</div>
						</div>
					</div>
</div>

{% block extrajs %}
<script src="{% static 'jquery/jquery.min.js' %}"></script>
<script src="{% static 'js_mactor/consultas_ajax.js' %}"></script>
<script src="{% static 'js_mactor/consultas_ajax2.js' %}"></script>
{% endblock %}

{% endblock %}